### ISSUE TITLE
Fallback to CPU-only when no nvidia GPU is detected

### ISSUE THREAD

**Issue by talent-less** [ehfd/docker-nvidia-glx-desktop#12]
Currently the container will crash when no  GPU is detected
https://github.com/ehfd/docker-nvidia-glx-desktop/blob/main/bootstrap.sh#L59

Is it possible to fallback to CPU-only X server when no nvidia GPU is detected?

**Comment by ehfd** [comment]
The type of X11 server used in this repository requires an NVIDIA driver. Software fallback is supported in https://github.com/ehfd/docker-nvidia-egl-desktop.
