### ISSUE TITLE
Troubleshooting help - unable to access VNC session in Kubernetes

### ISSUE THREAD

**Issue by iotify-sean** [ehfd/docker-nvidia-glx-desktop#13]
I need a little help troubleshooting this container.

I got it working with `docker` using the one line command in provided in the documentation - no problems there.

I decided to set it up on a test (one node) k8s cluster - I set up the `nvidia/gpu-operator` and the GPU appears as a resource that can be claimed. I created some `yaml` which enables the container to be deployed and a `Nodeport` based service to connect to it.

The container comes up and seems to claim the GPU resources correctly (I can see `Xorg` when I run `nvidia-smi` and I can see all the X processes running inside the pod). I can connect to `guacamole` via the `Nodeport` and I'm able to log in.

When I try to connect to the VNC session via the browser, however, I see the following:

![Screenshot from 2021-08-28 17-38-36](https://user-images.githubusercontent.com/86295554/131223204-07e6cb68-6c71-4fbe-a3ca-fc9c4e7cc3ef.png)

I can see this in the tomcat logs:

```
10.244.0.1 - - [28/Aug/2021:15:39:25 +0000] "POST /tunnel?connect HTTP/1.1" 500 673
```
which seems to be at the crux of the issue.

However, I don't know where to look for more logs to try to understand why this 500 arises.

Can you tell me where I could find more info on how to determine the reason for this 500 response?

Thanks!

**Comment by iotify-sean** [comment]
So I found that there is a log file in `/tmp` which contains useful information on how the system comes up - perhaps that should be moved to `/var/log`?

Regarding the more substantive point of troubleshooting the issue - I found that in my setup `guacd` comes up on IPv6 `localhost` (`::1`) but the client was (presumably) trying to connect via IPv4 `localhost` - I added `/etc/guacamole/guacd.conf` inside the container which explicitly specified that `guacd` should run on `0.0.0.0` and everything worked.

**Comment by ehfd** [comment]
Resolved.
