### ISSUE TITLE
Audio through Apache Guacamole

### ISSUE THREAD

**Issue by johncadengo** [ehfd/docker-nvidia-glx-desktop#15]
Is it possible to get audio through the web browser session in Apache Guacamole? I can see that pulse audio is started and listening on the right port. I don't know what's the next step to enable audio to go through the VNC session.

**Comment by ehfd** [comment]
You should already have it. Try running a youtube video with the volume on top right up.

**Comment by johncadengo** [comment]
Ok, I see. It might be worth noting, but the first time I tried it, I was using Safari on a Mac. So, once I switched to Firefox, it worked. I'm assuming Chrome is similar. But maybe there should be a note that audio doesn't come through on Safari by default. There might be a workaround and I'll let you know if I find one.

**Comment by ehfd** [comment]
Note that we are trying to change Guacamole to a different frontend because of performance issues. We are aiming to improve enough to gain the potential of the GPU.

**Comment by johncadengo** [comment]
Ok I see. Just curious, why move from the previous noVNC solution to Guacamole? What are the options you're exploring now?

**Comment by ehfd** [comment]
Audio support is only available in guacamole, so we moved over to noVNC. I can't disclose the option we are looking at right now, but it will be a big improvement.

**Comment by ehfd** [comment]
Will close for now.

**Comment by johncadengo** [comment]
No problem. Is there a tag I can use to work off the of the most recent version before it was switched to guacamole? NoVNC seemed to work well for my purposes but guacamole, as you mentioned, doesn't take full advantage of the GPU and the rendering is a bit slower.

**Comment by ehfd** [comment]
https://github.com/ehfd/docker-nvidia-glx-desktop/tree/cad675fd56d40da26f4556d53bb58c2f9ee2f136

Ubuntu 18.04 support may not be implemented.

**Comment by ehfd** [comment]
Implemented through Selkies.
