### ISSUE TITLE
Please Post Minor Feature Requests or Regression Reports Here

### ISSUE THREAD

**Issue by findmyway** [ehfd/docker-nvidia-glx-desktop#23]
Current `cudagl` version is hardcoded in the dockerfile. How about turning it into an `ARG` and enabling it in the GitHub workflow?

**Comment by ehfd** [comment]
Will consider for the next update, thanks.

**Comment by ehfd** [comment]
Will make adjustments together when the next version for selkies-gsteamer is out.

**Comment by ehfd** [comment]
It has been done.
However, due to the following issues, the following section in the Dockerfile was required and may present issues the next time the base image is updated. As this is relevant to this issue, I am keeping this issue open.
https://github.com/NVIDIA/nvidia-docker/issues/1632
https://gitlab.com/nvidia/container-images/cuda/-/issues/158
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771/12
```
# Temporary fix for NVIDIA container repository
RUN apt-get clean && \
    apt-key adv --fetch-keys "https://developer.download.nvidia.com/compute/cuda/repos/$(cat /etc/os-release | grep '^ID=' | awk -F'=' '{print $2}')$(cat /etc/os-release | grep '^VERSION_ID=' | awk -F'=' '{print $2}' | sed 's/[^0-9]*//g')/x86_64/3bf863cc.pub" && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by ehfd** [comment]
Note that the MATE Desktop is incompatible with Xorg in the default repositories combined with NVIDIA drivers >= 495, therefore the desktop environment was changed to Xfce.

**Comment by Aerosane** [comment]
Hello,

when I open the port 8080(selkies-gstreamer) URL,I get “502 Bad gateway “ error from nginx,

Thank you,

**Comment by Aerosane** [comment]
Is it possible for having GNOME desktop? As it’s much optimized than xfce and ideal for many Ubuntu operations?

**Comment by ehfd** [comment]
> Is it possible for having GNOME desktop? As it’s much optimized than xfce and ideal for many Ubuntu operations?

1. Inefficient over remote access protocols.
2. It has a known issue where there is no EDID, the desktop environment scales to (I think) 1280x768 with many workarounds ro make it work on an on demand resolution.
Therefore GNOME is not commonly used in containers. MATE has a separate issue related to Xorg written above.
https://github.com/mviereck/x11docker#examples
These are the list of tested DEs on Docker, and Xfce has the best graphics and support out of all.

**Comment by ehfd** [comment]
Current docs are too hard to comprehend, even for me. Will update to become more simple.

**Comment by ehfd** [comment]
A lot of this issue has been addressed in the latest commits. Closing.
Ubuntu 22.04 will be supported after nvidia/cudagl image is released.
