### ISSUE TITLE
[Fix] No screens found / Failed to acquire modesetting permission

### ISSUE THREAD

**Issue by ayunami2000** [ehfd/docker-nvidia-glx-desktop#26]
adding `Option "UseDisplayDevice" "none"` to the Xorg config seems to fix this issue, but as someone who is not a complete expert with linux or sed, I am opening an issue instead of a pull request.

**Comment by ehfd** [comment]
Did you set a resolution over 1920x1200? If so, you need to set the VIDEO_PORT envvar to something like "DP-0".

And no, there is a reason that I did not set the display device to "none". RANDR will be completely disabled if so and a lot of graphics workloads will be unavailable to run.

**Comment by ehfd** [comment]
I will add an option to set `Option "UseDisplayDevice" "none"` using environment variables.

**Comment by ehfd** [comment]
Will be implemented.
