### ISSUE TITLE
XDG_RUNTIME_DIR not set, + vulkan issues

### ISSUE THREAD

**Issue by ayunami2000** [ehfd/docker-nvidia-glx-desktop#27]
1) XDG_RUNTIME_DIR is not set. It can be set manually by passing `-e XDG_RUNTIME_DIR=/tmp`
2) `vkcube` and `vulkaninfo` both fail:
![image](https://user-images.githubusercontent.com/24785136/185335754-5b819749-1403-4672-b2d5-a624e55fff01.png)
![image](https://user-images.githubusercontent.com/24785136/185335776-e8c080ec-2a67-4249-90c1-bc0bc91885b7.png)
3) SteamVR fails, probably due to the above ^ issue with Vulkan, but I'm not sure.

GPU is a 3090 on RunPod. Similar issues on Vast.ai.

**Comment by ayunami2000** [comment]
Vulkan issues were fixed after installing `aptitude` then running `sudo aptitude install nvidia-driver-515=515.48.07-0ubuntu1 libnvidia-gl-515=515.48.07-0ubuntu1 nvidia-dkms-515=515.48.07-0ubuntu1 libnvidia-compute-515=515.48.07-0ubuntu1 libnvidia-extra-515=515.48.07-0ubuntu1 nvidia-compute-utils-515=515.48.07-0ubuntu1 libnvidia-decode-515=515.48.07-0ubuntu1 libnvidia-encode-515=515.48.07-0ubuntu1 nvidia-utils-515=515.48.07-0ubuntu1 xserver-xorg-video-nvidia-515=515.48.07-0ubuntu1 libnvidia-cfg1-515=515.48.07-0ubuntu1 libnvidia-fbc1-515=515.48.07-0ubuntu1 libnvidia-common-515=515.48.07-0ubuntu1 nvidia-kernel-common-515=515.48.07-0ubuntu1`

**Comment by ehfd** [comment]
1. So far, I had no issues without `XDG_RUNTIME_DIR` set.
2. You need to use nvidia-docker2 or NVIDIA/k8s-device-plugin for this to properly work. Please confirm you have this applied outside the container.

**Comment by ayunami2000** [comment]
Apparently, applications are supposed to handle when `XDG_RUNTIME_DIR` is not set, but ALVR crashes (lol). OpenGL works (`glxgears`) and `nvidia-smi` works as well. I'm not sure about how they are running it with the GPU (2), but I'll give `sudo ubuntu-drivers autoinstall` a try (3).

**Comment by ayunami2000** [comment]
Ok, I've run `sudo ubuntu-drivers autoinstall`, and I got this.
![image](https://user-images.githubusercontent.com/24785136/185457779-4317728c-8c20-40af-b80a-5829a5460553.png)
![image](https://user-images.githubusercontent.com/24785136/185457804-6dd12911-9177-40ba-b08e-4ab64c35b758.png)
![image](https://user-images.githubusercontent.com/24785136/185457866-181b4d9c-edf6-439d-b710-b29b0e3a32a5.png)

**Comment by ayunami2000** [comment]
Update (this had better not be it): Possibility that I had used the other repo (the `egl` one) instead. Checking now to be sure.

**Comment by ehfd** [comment]
> Ok, I've run sudo ubuntu-drivers autoinstall, and I got this.
I meant outside the container in the host. The host has to be properly configured. 
Consult this: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

**Comment by ayunami2000** [comment]
![image](https://user-images.githubusercontent.com/24785136/185704022-e147037e-6d52-46d9-b3be-b76959e01b5d.png)

The host meets the requirements. It's very likely something wrong with the docker image, not the host. (but I could be wrong)

**Comment by ehfd** [comment]
DO NOT install your own drivers. The startup script is supposed to install it for you.
In a clean nvidia-glx-desktop container with no modifications after startup get the following outputs:
`glxinfo | head`
`glxgears -info` (get the first 50 lines)
`nvidia-smi`
Let's start from here.

**Comment by ehfd** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/1480#issuecomment-964285018
This is the issue. In `NVIDIA_DRIVER_CAPABILITIES` `compute,utility,video,graphics,display` must all be there or simply use `all`.

**Comment by ehfd** [comment]
To include in documentation.

**Comment by ehfd** [comment]
Will be added in docs.
