### ISSUE TITLE
Quick clarifications

### ISSUE THREAD

**Issue by johncadengo** [ehfd/docker-nvidia-glx-desktop#30]
Hi @ehfd, appreciate all your work on this. I used an older version of this repo awhile back and wanted to see how it's been improved since then so I ran some tests last night. 

Quick questions:

- Do you have to stop gdm/ligthdm if it's already running on your current machine? Not sure this is clear in the documentation, but I found by stopping it, I could get the container to work. But when gdm was already running, the container would not work.
- I was able to get the egl version of this container running, but not all apps would work off of it (like Firefox). However, when I'm in the glx version, I can clearly see Firefox running off the gpu by checking `nvidia-smi` for running processes. Does the egl version only support certain software out of the box?
- Is egl the only one that can support multiple containers running off of the same gpu? Or is that possible with glx as well? If not, what stops it from working with glx?

**Comment by ehfd** [comment]
> Do you have to stop gdm/ligthdm if it's already running on your current machine? Not sure this is clear in the documentation, but I found by stopping it, I could get the container to work. But when gdm was already running, the container would not work.
https://github.com/ehfd/docker-nvidia-glx-desktop#the-container-doesnt-work-if-an-existing-gui-or-x-server-is-running-in-the-host-outside-the-container--i-want-to-use---privileged-mode-or---cap-add-to-my-containers

> I was able to get the egl version of this container running, but not all apps would work off of it (like Firefox). However, when I'm in the glx version, I can clearly see Firefox running off the gpu by checking nvidia-smi for running processes. Does the egl version only support certain software out of the box?

The EGL repository is not perfect, and depends on VirtualGL capabilities.https://github.com/VirtualGL/virtualgl/issues/177 https://github.com/VirtualGL/virtualgl/issues/186
As you see here, VirtualGL 3.1, which isn't even released, is required, but currently we are at 3.0.1, which is the latest official release.

> Is egl the only one that can support multiple containers running off of the same gpu? Or is that possible with glx as well? If not, what stops it from working with glx?
One GPU for one X server. Limitation of the NVIDIA driver. EGL doesn't use the NVIDIA X server and instead uses Xvfb, so it is free of the restriction. More information available in the docs.

Please leave a message here or use our [Discord](https://discord.gg/wDNGDeSW5F) and ping me for more discussion.
