### ISSUE TITLE
Wine application or game issues

### ISSUE THREAD

**Issue by loochek** [ehfd/docker-nvidia-glx-desktop#33]
For example, when running `winecfg` I get such message:
```
00d0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00d0:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
```
How can I fix it?

**Comment by ehfd** [comment]
@loochek What is the application that you are trying to run? What are the complete logs? Have you tried any solution that comes out when you search this error in Google?

**Comment by ehfd** [comment]
+ You might need a prefix for it. Try Lutris to configure and start Wine programs.

**Comment by loochek** [comment]
Sorry for the late response
Seems that more serious errors are present
[wine.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9754934/wine.log)
This log generated by stock wine from the image (wine-staging 7.18). Wine-stable from winehq gives the same error. But Wine from Ubuntu repo (5.x) works without any errors.

**Comment by ehfd** [comment]
I get winecfg with an unmodified version of this desktop.

**Comment by ehfd** [comment]
Alright, I am reprofiling this issue to fix various Wine issues.
**Please post issues related to Wine not running or applications on Wine, VKD3D-Proton, DXVK, etc. showing erratic behaviors related to the graphic device or framerate. Please post issues related to the cursors in https://github.com/selkies-project/selkies-gstreamer/issues/28.**

The issues I see while testing various games that my colleagues lent me for testing, where Wine failed to start (continuously updated):
Elden Ring (VKD3D): Does not start if `export __NV_PRIME_RENDER_OFFLOAD=1` is set. Must not set this. Still shows a message about framerate issues, but offline playing is possible.

**Comment by ehfd** [comment]
Lutris removed their PPAs. Therefore, the container build will fail. Please wait a bit for the fix.

**Comment by ehfd** [comment]
I think I made Wine stable enough. `winecfg` works well when running right at container start. Please reopen if there are more issues.
