### ISSUE TITLE
support plain vnc alongside selkies

### ISSUE THREAD

**Issue by nick008a** [ehfd/docker-nvidia-glx-desktop#35]
Is it possible to connect with for example, realVNC to this container when selkies is running?

**Comment by ehfd** [comment]
https://github.com/ehfd/docker-nvidia-glx-desktop/blob/main/entrypoint.sh#L118
`x11vnc -display "${DISPLAY}" -passwd "${BASIC_AUTH_PASSWORD:-$PASSWD}" -shared -forever -repeat -xkb -snapfb -threads -xrandr "resize" -rfbport 5900 ${NOVNC_VIEWONLY}`

Run this line manually (replace the environment variables), and expose port 5900.

**Comment by ehfd** [comment]
This will not be supported by default.
