### ISSUE TITLE
Multiple GPUs, for multiple VNC desktop

### ISSUE THREAD

**Issue by LiangHuangBC** [ehfd/docker-nvidia-glx-desktop#7]
We have one Gpu server with 4 Gpus. There are 4 developers want to use these Gpus, one for each. But we can only open one vnc desktop at the same time, when we open second, the first one will go black. Command I tried:    
docker run --name glx1 -d --gpus "device=1" --privileged -it -e SIZEW=1920 -e SIZEH=1080 -e SHARED=TRUE -e VNCPASS=vncpasswd -p 5902:5901 ehfd/nvidia-glx-desktop:latest 
By this command, we can run program on second gpu, but can not work together with the first container running on --gpus "device=0".   The first container will go black when second container start, even they are not on same gpu.

Also tried command without privileged:
docker run --name glx1 -d --gpus "device=1" --device=/dev/tty1:rw -it -e SIZEW=1920 -e SIZEH=1080 -e SHARED=TRUE -e VNCPASS=vncpasswd -p 5902:5901 ehfd/nvidia-glx-desktop:latest
By this command, x11vnc can not start up. Error is could't open display.

And tried command in README, tried to open two vnc on same gpu 0, no luck.  

And btw, there is small issue in bootstrap.sh, when docker restart your container, bootstrap will stuck on re-install driver.  We fixed it by commenting it out.

**Comment by ehfd** [comment]
@LiangHuangBC I googled and noticed `--gpus '"device=1"'` is the correct syntax. Other than that, could you post the contents of `/etc/X11/Xorg.conf` on both containers?

**Comment by ehfd** [comment]
Please use `--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0` or `--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=GPU-e8372....` instead. Tested in Docker 19.03.

**Comment by ehfd** [comment]
> By this command, we can run program on second gpu, but can not work together with the first container running on --gpus "device=0". The first container will go black when second container start, even they are not on same gpu.

This is unfixable because of how Xorg works. Please wait until the NVIDIA 470.xx drivers are out and Xwayland is compatible.

In the meantime, use https://github.com/ehfd/docker-nvidia-egl-desktop if you are using OCI containers from cluster orchestration platforms like Kubernetes or Mesos and https://github.com/mviereck/x11docker if you are using docker from one single node with full root permissions.

**Comment by ehfd** [comment]
Fixed code to work in privileged mode. Please test and tell me.
> bootstrap will stuck on re-install driver
Please feedback on this too. It shouldn't be stuck.

**Comment by ehfd** [comment]
In progress of fixing this issue.

**Comment by ehfd** [comment]
Fixed in commit 1fbae34

Please consult the new instructions. Privileged mode is no longer supported in favor of unprivileged containers.

**Comment by ehfd** [comment]
Added in [Documentation](https://github.com/ehfd/docker-nvidia-glx-desktop#troubleshooting).
