### ISSUE TITLE
Can't load fullscreen games

### ISSUE THREAD

**Issue by johncadengo** [ehfd/docker-nvidia-glx-desktop#8]
I'm able to get this container up and running and run any 64-bit application. But when I try running 32-bit applications, I can't get anything to display. For example, I tried running `0ad` and although it prints out logs to the terminal, I see nothing on the screen. If I run Wine applications that are 32-bit (games mostly) they won't display anything either. Is there something I can do to enable the 32-bit drivers from Nvidia in this container?

For reference: https://github.com/nvidia/nvidia-container-runtime#nvidia_driver_capabilities

I tried setting the environment variable `NVIDIA_DRIVER_CAPABILITIES=all` but I did not see any effect. I'm not sure how to test whether or not the 32-bit libraries are being included in this container.

**Comment by johncadengo** [comment]
By the way, I was wondering if it was an OpenGL vs Vulkan issue, so I ran a test: https://github.com/srmojuze/Refresh2025

I was able to run this demo in every combination of modes between OpenGL or Vulkan and windowed or fullscreen.

But I cannot get 0ad to run, which I installed via `sudo apt install 0ad` and running through the terminal command `0ad`.

**Comment by johncadengo** [comment]
Ok, maybe this is less to do with 32-bit and more to do with fullscreen vs windowed.

Following a trail I found here (https://wildfiregames.com/forum/topic/24481-solved-how-to-reliably-start-the-game-in-windowed-mode/?tab=comments#comment-357175). I updated the `~/.config/0ad/config/user.cfg` file and added the line

```
windowed = true
```

Upon changing it to that, I was able to get 0ad to load up. I clicked around the menu, things worked. I loaded a game, it worked.

However, not all games support windowed mode, and I am still having trouble loading those games. Do you know why fullscreen wouldn't load, but windowed would? By default, most games load in full screen, and 0ad would have a new panel item, but show nothing. It's not a blank screen. I still see the Mate desktop and can click around and do things. It just doesn't load any visuals of the game.

**Comment by johncadengo** [comment]
Ok, one more clue. I ran 0ad in fullscreen mode (by removing `windowed=true` from the config file), and supplying this env variable:

`$ SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 0ad`

At this point, I'm able to see the menu, but I cannot click anything.

**Comment by ehfd** [comment]
I tried 0ad. The mouse and the windiw does not coordinate and I had to click a bit below that to click the screen. It will be solved if you change to windowed. For any other fullscreen programs as well it is recommended to use borderless window equal to the size of the screen.

**Comment by johncadengo** [comment]
@ehfd thanks for the info. Looking forward to the improved implementation with XWayland, which will be interesting.

By the way, what's the trick to get multiple Xorgs running, 1 per container, under this implementation? I could not achieve that with other docker containers and it's interesting to be able to do that with this container.

**Comment by ehfd** [comment]
@johncadengo It's another hack. I did some experiments and when all containers are privileged mode AND shares the same TTY multiple Xorg instances work.

**Comment by ehfd** [comment]
Closing as this is not fixable because of Xorg issues.

**Comment by ehfd** [comment]
In progress of fixing this issue.

**Comment by ehfd** [comment]
Fixed in commit https://github.com/ehfd/docker-nvidia-glx-desktop/commit/1fbae346a2a530ebbcb36bec66e3869b08e440b8

Fullscreen capability tested in 0ad, GFXBench, and Unigine Superposition.
Please consult the new instructions. Privileged mode is no longer supported in favor of unprivileged containers.

**Comment by johncadengo** [comment]
@ehfd Thanks for the update. Excited to see how these new changes work. Also curious, how does this container now compare to the egl version. Is the egl one still the recommended one in most cases besides vulkan support?

**Comment by ehfd** [comment]
EGL has a simpler container design. This means it is less prone to fail in edge cases. However it doesn't support RandR better than GLX in addition to no Vulkan, and 0ad for example still doesn't fit its window to the screen correctly in EGL.

For Kubernetes honestly, GLX has actually become better to manage. And if you set VIDEO_PORT to a connected monitor, it will be able to use a physical monitor at the same time as well, although not tested. This is also something to take carefully if the GPU is not headless, since a desktop screen will be sent out to a monitor on accident. I also have to test in a Tesla GPU to see how this works.

**Comment by ehfd** [comment]
Added in [Documentation](https://github.com/ehfd/docker-nvidia-glx-desktop#troubleshooting).
`VIDEO_PORT` must be set to `DFP` or `DP-0`, `DP-1`, ... based on circumstances to achieve full screen.
