### ISSUE TITLE
Skip driver installation when starting the container for the second time

### ISSUE THREAD

**Issue by talent-less** [ehfd/docker-nvidia-glx-desktop#9]
Can bootstrap.sh detect and skip the driver installation  when starting the container for the second time?

https://github.com/ehfd/docker-nvidia-glx-desktop/blob/main/bootstrap.sh#L10

**Comment by ehfd** [comment]
Will investigate. But I am a bit busy until mid-June.

**Comment by ehfd** [comment]
Fixed in commit https://github.com/ehfd/docker-nvidia-glx-desktop/commit/1fbae346a2a530ebbcb36bec66e3869b08e440b8

Please consult the new instructions. Privileged mode is no longer supported in favor of unprivileged containers.
